### PR TITLE
Add crow foot notations to describe relations between objects

### PR DESCRIPTION
**Pull request by confususs**
First a big disclaimer, I'm very new in this library so I don't know if this is the correct way to implement these changes. I wanted to create a PR so you can check it out.

This change basically introduces a way to describe what kind of relations there are between objects. 

relation_notations

Ideally we would use something similar to what bpmn-js is doing, with a nested menu within a contextpad item, but that seemed very complex to implement. For now this will at least provide a way to describe the relations between objects. 

Let me know what you think :slightly_smiling_face:. Also, feel free to change things!

### CODE REVIEW

**Comment by timKraeuter** [comment]
Hi,

Thanks for the pull request!

I was wondering what the crowfoot notations are supposed to show us. I have never seen them before in object diagrams (only in database schemas).
Object diagrams are never defined explicitly in the [UML specification](https://www.omg.org/spec/UML/2.5.1/About-UML/), but I took 9.8 as a rough reference.

Should the relations between objects such as "one-or-many" not be defined using _multiplicities_, i.e., 0..* in the associated class diagram?

**Comment by confususs** [comment]
Following the examples mentioned in the UML specification, it seems using multiplicities would be the way to go indeed, but I do like the clarity the crow foot notation provides. 

One thing a colleague mentioned to me is an excerpt from 7.2.4:

> There is no general notation for Element, Relationships, and DirectedRelationships. The descendants of these classes
define their own notation. For Relationships, in most cases the notation is a variation on a line drawn between the
relatedElements. For DirectedRelationships, the line is usually directed in some way from the source(s) to the target(s).

Which seems to provide quite some flexibility in how relationships can be described. :innocent:  

However, it might be that I'm looking more for relation notations for class diagrams rather than relation notations for object diagrams.

Either way, I totally understand that this change might not be something that you'd like to have merged, since this change is less likely to follow the spec.

**Comment by timKraeuter** [comment]
Yes, I think the crow-foot notation is nice but belongs on the **model level** where class diagrams and database schemas reside.

I don't think it makes sense on the **instance level** where object diagrams are located. However, I was also thinking about implementing a class diagram editor. It would be great to have the crow-foot notation as an alternative to multiplicities.

**Comment by confususs** [comment]
Agreed! I'll close this MR. Thanks for taking the time to check out the change and for thinking along. Perhaps at some point we can collaborate on the class diagram editor :slightly_smiling_face:

**Pull request closed without merging**
